### PR TITLE
Ath 1104 navigate to posts list after updating

### PR DESCRIPTION
**Pull request by mckhannah1901**
### JIRA
[ATH-1104: Navigate to Posts List after Editing](https://wpengine.atlassian.net/secure/RapidBoard.jspa?rapidView=522&projectKey=ATH&modal=detail&selectedIssue=ATH-1104)

### What Has Been Done
The user is now redirected to the posts list after editing a post

### How to verify
1. Verify that a non logged in user can only view blog posts but can't edit them
2. Log in as a user
3. View the list of posts
4. Select the edit button on the post you'd like to edit
5. Fill in the form and publish
6. If successful, a flash message will tell you the post has been updated successfully and will redirect to the list of posts

### CODE REVIEW

**Comment by alvarocavalcanti** [comment]
After editing the blog post the **flash message did not appear**.

**Comment by alvarocavalcanti** [comment]
This PR depends on #9 and thus you should stop adding changes to it. Let's wait until #9 is merged and then you can resume the work here.

**Comment by alvarocavalcanti** [comment]
Since you've merged #9 now you need to merge master into this branch.

**Comment by mckhannah1901** [comment]
> Since you've merged #9 now you need to merge master into this branch.

I've already merged master into this branch

**Comment by alvarocavalcanti** [comment]
But have you pushed the merge afterwards?

**Comment by mckhannah1901** [comment]
Everything is up to date 👍

**Pull request closed without merging**
